spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: lynx-wrs

  flyway:
    enabled: true
    locations: classpath:db/migration


  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: lynx
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}